package com.github.petruki.battleship.broker;

public enum BrokerEvents {
	CHECK_CREATE_ROOM,
	PLAYER_HAS_JOINED,
	PLAYER_HAS_DISCONNECTED,
	PLAYER_HAS_SHOT,
	ROOM_DATA,
	MATCH_STARTED,
	NEW_ROUND,
	SELECT_PLAYER,
	NOTIFY_EVENT
}
